### ISSUE TITLE
Port to Zope 4

### ISSUE THREAD

**Issue by icemac** [zopefoundation/Products.FSDump#2]
So, I restarted following the zdg.2 to develop FSDump, added "src" and adapted its setup.py to include directory "src" (for what purpose? convention?). Anyway, with or without "src", I get the setuptools error:
```
File "~/fsdump/zope4/eggs/Zope-4.1-py3.8.egg/OFS/Application.py", line 389, in import_product
product = __import__("Products.%s" % product_name,
File "~/fsdump/Products.FSDump/src/Products/FSDump/__init__.py", line 5, in <module>
from Products.FSDumper.Dumper import Dumper, addDumperForm, addDumper
ModuleNotFoundError: No module named 'Products.FSDumper'

```
My fork for FSDump is up to date, if one of you wants to have a look. I put there also buildout.cfg. I guess next is to read about python packaging <sigh>.

_Originally posted by @ghiodor in https://github.com/zopefoundation/Zope/issues/252#issuecomment-505284862_

**Comment by icemac** [comment]
@ghiodor Line 5 of contains an error: The module is called `FSDump` not `FSDumper`, so the line has to read: `from Products.FSDumper import Dumper`.

**Comment by ghiodor** [comment]
Thanks @icemac, that fixed the problem. I pushed my latest changes to my forked version. Currently it is possible to add a FSDump object to the database. I will keep working on it.

**Comment by icemac** [comment]
The actual issue is solved so I closed this issue even though the port is not yet complete.

**Comment by ghiodor** [comment]
With a few more fixes the port generally works. Only tested the index_html object. Is there a public Data.fs that I could use for further testing? My goal now is to do implement the reverse operation.

**Comment by icemac** [comment]
I do not know of a publicly available Data.fs which can be used for testing. At least creating a toy database for testing should not be that hard.
