### ISSUE TITLE
pip installs Python 2 Version

### ISSUE THREAD

**Issue by georgpfolz** [zopefoundation/Products.FSDump#4]
In the newest installation from pip, you get the error: "ModuleNotFoundError: No module named 'Dumper'"

This is due to the import line in *__init__.py*: `import Dumper` which should be `from Products.FSDump import Dumper`.

But even after correcting this, you get some errors like 'raise "Dumper Error", "Path must be absolute."'

So it seems the version installed is Python 2 code.

Luckily I had an older version installed elsewhere, which works fine (with Python 3.8).

**Comment by icemac** [comment]
It seems that this package is not yet ported to Python 3.
I created #5 to track the Python 3 migration, so closing this issue here.
